# Generated by Django 3.2.4 on 2021-07-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_req_list',
            field=models.ManyToManyField(blank=True, related_name='sent_friend_req_list', to='users.Profile'),
        ),
    ]
