# Generated by Django 3.2.4 on 2021-06-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210623_0635'),
        ('blog', '0002_auto_20210623_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='downvoted',
            field=models.ManyToManyField(blank=True, related_name='downvoted_blogs', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='blog',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoted_blogs', to='users.Profile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('blog_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
        ),
    ]
