# Generated by Django 3.2.4 on 2021-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210623_0635'),
        ('blog', '0003_auto_20210623_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvoted',
            field=models.ManyToManyField(blank=True, related_name='downvoted_comments', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoted_comments', to='users.Profile'),
        ),
    ]
